Implement and test Money as well as Percentage class
dhbw-stginf16a/java-banking1 pull request #24
Opened 2017-05-29 17:04 UTC by JohnAZoidberg

Resolves #11 s

2017-05-29 18:09 UTC, guserav requested changes
@amilabell Please change the implementation of applyPercentage()

and some minor javaDoc issues

2017-05-29 18:09 UTC, guserav commented on src/main/java/banking/backend/Money.java
> +            throw new IllegalArgumentException("Number is not in the format ###,###.##");
The Exception text doesn't fit for the given parameters, because the format implies that a String was parsed.

2017-05-29 18:09 UTC, guserav commented on src/main/java/banking/backend/Money.java
>       * Returns a new instance of Money with the value of this minus amount.
Please change "amount" into "money"

2017-05-29 18:09 UTC, guserav commented on src/main/java/banking/backend/Money.java
> +        money.cents = this.cents * (percentage.getPercentage() / 100) / 100;
int / int results in int so the result is rounded before further operators are aplied

2017-05-29 18:09 UTC, guserav commented on src/main/java/banking/backend/Money.java
>      }
Method doesn't work as expected, Please change it to perform the operation = money * (100% + Percentage)

2017-05-29 18:09 UTC, guserav commented on src/test/java/banking/backend/MoneyTest.java
> +                new Money(1).applyPercentage(new Percentage(105)));
Test tests wrong cases please change this to
`new Money(1, 5), `
`new Money(1).applyPercentage(new Percentage(5)));`

2017-05-29 18:31 UTC, JohnAZoidberg commented on src/main/java/banking/backend/Money.java
>      }
I guess we should rename it at percentage.

2017-05-29 18:33 UTC, JohnAZoidberg commented on src/main/java/banking/backend/Money.java
>       * Returns a new instance of Money with the value of this minus amount.
Are you requesting a change back?

2017-05-29 18:48 UTC, guserav commented on src/main/java/banking/backend/Money.java
>      }
If you want to fix the usage of it you are more than welcome to rename it.

2017-05-30 09:10 UTC, guserav submitted a review, later dismissed

2017-05-30 09:12 UTC, guserav commented on src/test/java/banking/backend/MoneyTest.java
> +                new Money(1).applyPercentage(new Percentage(-5)));
This seems wrong

2017-05-30 09:14 UTC, guserav commented on src/test/java/banking/backend/MoneyTest.java
> +                new Money(1).applyPercentage(new Percentage(-5)));
overlocked Not

2017-05-30 09:15 UTC, guserav approved these changes
All is fine

2017-05-30 09:15 UTC, merged